/*
 * Copyright (C) 2012 Grigori Goronzy <greg@kinoho.net>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef UCDN_H
#define UCDN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define UCDN_EAST_ASIAN_F 0
#define UCDN_EAST_ASIAN_H 1
#define UCDN_EAST_ASIAN_W 2
#define UCDN_EAST_ASIAN_NA 3
#define UCDN_EAST_ASIAN_A 4
#define UCDN_EAST_ASIAN_N 5

#define UCDN_SCRIPT_COMMON 0
#define UCDN_SCRIPT_LATIN 1
#define UCDN_SCRIPT_GREEK 2
#define UCDN_SCRIPT_CYRILLIC 3
#define UCDN_SCRIPT_ARMENIAN 4
#define UCDN_SCRIPT_HEBREW 5
#define UCDN_SCRIPT_ARABIC 6
#define UCDN_SCRIPT_SYRIAC 7
#define UCDN_SCRIPT_THAANA 8
#define UCDN_SCRIPT_DEVANAGARI 9
#define UCDN_SCRIPT_BENGALI 10
#define UCDN_SCRIPT_GURMUKHI 11
#define UCDN_SCRIPT_GUJARATI 12
#define UCDN_SCRIPT_ORIYA 13
#define UCDN_SCRIPT_TAMIL 14
#define UCDN_SCRIPT_TELUGU 15
#define UCDN_SCRIPT_KANNADA 16
#define UCDN_SCRIPT_MALAYALAM 17
#define UCDN_SCRIPT_SINHALA 18
#define UCDN_SCRIPT_THAI 19
#define UCDN_SCRIPT_LAO 20
#define UCDN_SCRIPT_TIBETAN 21
#define UCDN_SCRIPT_MYANMAR 22
#define UCDN_SCRIPT_GEORGIAN 23
#define UCDN_SCRIPT_HANGUL 24
#define UCDN_SCRIPT_ETHIOPIC 25
#define UCDN_SCRIPT_CHEROKEE 26
#define UCDN_SCRIPT_CANADIAN_ABORIGINAL 27
#define UCDN_SCRIPT_OGHAM 28
#define UCDN_SCRIPT_RUNIC 29
#define UCDN_SCRIPT_KHMER 30
#define UCDN_SCRIPT_MONGOLIAN 31
#define UCDN_SCRIPT_HIRAGANA 32
#define UCDN_SCRIPT_KATAKANA 33
#define UCDN_SCRIPT_BOPOMOFO 34
#define UCDN_SCRIPT_HAN 35
#define UCDN_SCRIPT_YI 36
#define UCDN_SCRIPT_OLD_ITALIC 37
#define UCDN_SCRIPT_GOTHIC 38
#define UCDN_SCRIPT_DESERET 39
#define UCDN_SCRIPT_INHERITED 40
#define UCDN_SCRIPT_TAGALOG 41
#define UCDN_SCRIPT_HANUNOO 42
#define UCDN_SCRIPT_BUHID 43
#define UCDN_SCRIPT_TAGBANWA 44
#define UCDN_SCRIPT_LIMBU 45
#define UCDN_SCRIPT_TAI_LE 46
#define UCDN_SCRIPT_LINEAR_B 47
#define UCDN_SCRIPT_UGARITIC 48
#define UCDN_SCRIPT_SHAVIAN 49
#define UCDN_SCRIPT_OSMANYA 50
#define UCDN_SCRIPT_CYPRIOT 51
#define UCDN_SCRIPT_BRAILLE 52
#define UCDN_SCRIPT_BUGINESE 53
#define UCDN_SCRIPT_COPTIC 54
#define UCDN_SCRIPT_NEW_TAI_LUE 55
#define UCDN_SCRIPT_GLAGOLITIC 56
#define UCDN_SCRIPT_TIFINAGH 57
#define UCDN_SCRIPT_SYLOTI_NAGRI 58
#define UCDN_SCRIPT_OLD_PERSIAN 59
#define UCDN_SCRIPT_KHAROSHTHI 60
#define UCDN_SCRIPT_BALINESE 61
#define UCDN_SCRIPT_CUNEIFORM 62
#define UCDN_SCRIPT_PHOENICIAN 63
#define UCDN_SCRIPT_PHAGS_PA 64
#define UCDN_SCRIPT_NKO 65
#define UCDN_SCRIPT_SUNDANESE 66
#define UCDN_SCRIPT_LEPCHA 67
#define UCDN_SCRIPT_OL_CHIKI 68
#define UCDN_SCRIPT_VAI 69
#define UCDN_SCRIPT_SAURASHTRA 70
#define UCDN_SCRIPT_KAYAH_LI 71
#define UCDN_SCRIPT_REJANG 72
#define UCDN_SCRIPT_LYCIAN 73
#define UCDN_SCRIPT_CARIAN 74
#define UCDN_SCRIPT_LYDIAN 75
#define UCDN_SCRIPT_CHAM 76
#define UCDN_SCRIPT_TAI_THAM 77
#define UCDN_SCRIPT_TAI_VIET 78
#define UCDN_SCRIPT_AVESTAN 79
#define UCDN_SCRIPT_EGYPTIAN_HIEROGLYPHS 80
#define UCDN_SCRIPT_SAMARITAN 81
#define UCDN_SCRIPT_LISU 82
#define UCDN_SCRIPT_BAMUM 83
#define UCDN_SCRIPT_JAVANESE 84
#define UCDN_SCRIPT_MEETEI_MAYEK 85
#define UCDN_SCRIPT_IMPERIAL_ARAMAIC 86
#define UCDN_SCRIPT_OLD_SOUTH_ARABIAN 87
#define UCDN_SCRIPT_INSCRIPTIONAL_PARTHIAN 88
#define UCDN_SCRIPT_INSCRIPTIONAL_PAHLAVI 89
#define UCDN_SCRIPT_OLD_TURKIC 90
#define UCDN_SCRIPT_KAITHI 91
#define UCDN_SCRIPT_BATAK 92
#define UCDN_SCRIPT_BRAHMI 93
#define UCDN_SCRIPT_MANDAIC 94
#define UCDN_SCRIPT_CHAKMA 95
#define UCDN_SCRIPT_MEROITIC_CURSIVE 96
#define UCDN_SCRIPT_MEROITIC_HIEROGLYPHS 97
#define UCDN_SCRIPT_MIAO 98
#define UCDN_SCRIPT_SHARADA 99
#define UCDN_SCRIPT_SORA_SOMPENG 100
#define UCDN_SCRIPT_TAKRI 101
#define UCDN_SCRIPT_UNKNOWN 102
#define UCDN_SCRIPT_BASSA_VAH 103
#define UCDN_SCRIPT_CAUCASIAN_ALBANIAN 104
#define UCDN_SCRIPT_DUPLOYAN 105
#define UCDN_SCRIPT_ELBASAN 106
#define UCDN_SCRIPT_GRANTHA 107
#define UCDN_SCRIPT_KHOJKI 108
#define UCDN_SCRIPT_KHUDAWADI 109
#define UCDN_SCRIPT_LINEAR_A 110
#define UCDN_SCRIPT_MAHAJANI 111
#define UCDN_SCRIPT_MANICHAEAN 112
#define UCDN_SCRIPT_MENDE_KIKAKUI 113
#define UCDN_SCRIPT_MODI 114
#define UCDN_SCRIPT_MRO 115
#define UCDN_SCRIPT_NABATAEAN 116
#define UCDN_SCRIPT_OLD_NORTH_ARABIAN 117
#define UCDN_SCRIPT_OLD_PERMIC 118
#define UCDN_SCRIPT_PAHAWH_HMONG 119
#define UCDN_SCRIPT_PALMYRENE 120
#define UCDN_SCRIPT_PAU_CIN_HAU 121
#define UCDN_SCRIPT_PSALTER_PAHLAVI 122
#define UCDN_SCRIPT_SIDDHAM 123
#define UCDN_SCRIPT_TIRHUTA 124
#define UCDN_SCRIPT_WARANG_CITI 125
#define UCDN_SCRIPT_AHOM 126
#define UCDN_SCRIPT_ANATOLIAN_HIEROGLYPHS 127
#define UCDN_SCRIPT_HATRAN 128
#define UCDN_SCRIPT_MULTANI 129
#define UCDN_SCRIPT_OLD_HUNGARIAN 130
#define UCDN_SCRIPT_SIGNWRITING 131
#define UCDN_SCRIPT_ADLAM 132
#define UCDN_SCRIPT_BHAIKSUKI 133
#define UCDN_SCRIPT_MARCHEN 134
#define UCDN_SCRIPT_NEWA 135
#define UCDN_SCRIPT_OSAGE 136
#define UCDN_SCRIPT_TANGUT 137
#define UCDN_SCRIPT_MASARAM_GONDI 138
#define UCDN_SCRIPT_NUSHU 139
#define UCDN_SCRIPT_SOYOMBO 140
#define UCDN_SCRIPT_ZANABAZAR_SQUARE 141
#define UCDN_SCRIPT_DOGRA 142
#define UCDN_SCRIPT_GUNJALA_GONDI 143
#define UCDN_SCRIPT_HANIFI_ROHINGYA 144
#define UCDN_SCRIPT_MAKASAR 145
#define UCDN_SCRIPT_MEDEFAIDRIN 146
#define UCDN_SCRIPT_OLD_SOGDIAN 147
#define UCDN_SCRIPT_SOGDIAN 148
#define UCDN_SCRIPT_ELYMAIC 149
#define UCDN_SCRIPT_NANDINAGARI 150
#define UCDN_SCRIPT_NYIAKENG_PUACHUE_HMONG 151
#define UCDN_SCRIPT_WANCHO 152

#define UCDN_BLOCK_NO_BLOCK 0
#define UCDN_BLOCK_BASIC_LATIN 1
#define UCDN_BLOCK_LATIN_1_SUPPLEMENT 2
#define UCDN_BLOCK_LATIN_EXTENDED_A 3
#define UCDN_BLOCK_LATIN_EXTENDED_B 4
#define UCDN_BLOCK_IPA_EXTENSIONS 5
#define UCDN_BLOCK_SPACING_MODIFIER_LETTERS 6
#define UCDN_BLOCK_COMBINING_DIACRITICAL_MARKS 7
#define UCDN_BLOCK_GREEK_AND_COPTIC 8
#define UCDN_BLOCK_CYRILLIC 9
#define UCDN_BLOCK_CYRILLIC_SUPPLEMENT 10
#define UCDN_BLOCK_ARMENIAN 11
#define UCDN_BLOCK_HEBREW 12
#define UCDN_BLOCK_ARABIC 13
#define UCDN_BLOCK_SYRIAC 14
#define UCDN_BLOCK_ARABIC_SUPPLEMENT 15
#define UCDN_BLOCK_THAANA 16
#define UCDN_BLOCK_NKO 17
#define UCDN_BLOCK_SAMARITAN 18
#define UCDN_BLOCK_MANDAIC 19
#define UCDN_BLOCK_SYRIAC_SUPPLEMENT 20
#define UCDN_BLOCK_ARABIC_EXTENDED_A 21
#define UCDN_BLOCK_DEVANAGARI 22
#define UCDN_BLOCK_BENGALI 23
#define UCDN_BLOCK_GURMUKHI 24
#define UCDN_BLOCK_GUJARATI 25
#define UCDN_BLOCK_ORIYA 26
#define UCDN_BLOCK_TAMIL 27
#define UCDN_BLOCK_TELUGU 28
#define UCDN_BLOCK_KANNADA 29
#define UCDN_BLOCK_MALAYALAM 30
#define UCDN_BLOCK_SINHALA 31
#define UCDN_BLOCK_THAI 32
#define UCDN_BLOCK_LAO 33
#define UCDN_BLOCK_TIBETAN 34
#define UCDN_BLOCK_MYANMAR 35
#define UCDN_BLOCK_GEORGIAN 36
#define UCDN_BLOCK_HANGUL_JAMO 37
#define UCDN_BLOCK_ETHIOPIC 38
#define UCDN_BLOCK_ETHIOPIC_SUPPLEMENT 39
#define UCDN_BLOCK_CHEROKEE 40
#define UCDN_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS 41
#define UCDN_BLOCK_OGHAM 42
#define UCDN_BLOCK_RUNIC 43
#define UCDN_BLOCK_TAGALOG 44
#define UCDN_BLOCK_HANUNOO 45
#define UCDN_BLOCK_BUHID 46
#define UCDN_BLOCK_TAGBANWA 47
#define UCDN_BLOCK_KHMER 48
#define UCDN_BLOCK_MONGOLIAN 49
#define UCDN_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED 50
#define UCDN_BLOCK_LIMBU 51
#define UCDN_BLOCK_TAI_LE 52
#define UCDN_BLOCK_NEW_TAI_LUE 53
#define UCDN_BLOCK_KHMER_SYMBOLS 54
#define UCDN_BLOCK_BUGINESE 55
#define UCDN_BLOCK_TAI_THAM 56
#define UCDN_BLOCK_COMBINING_DIACRITICAL_MARKS_EXTENDED 57
#define UCDN_BLOCK_BALINESE 58
#define UCDN_BLOCK_SUNDANESE 59
#define UCDN_BLOCK_BATAK 60
#define UCDN_BLOCK_LEPCHA 61
#define UCDN_BLOCK_OL_CHIKI 62
#define UCDN_BLOCK_CYRILLIC_EXTENDED_C 63
#define UCDN_BLOCK_GEORGIAN_EXTENDED 64
#define UCDN_BLOCK_SUNDANESE_SUPPLEMENT 65
#define UCDN_BLOCK_VEDIC_EXTENSIONS 66
#define UCDN_BLOCK_PHONETIC_EXTENSIONS 67
#define UCDN_BLOCK_PHONETIC_EXTENSIONS_SUPPLEMENT 68
#define UCDN_BLOCK_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT 69
#define UCDN_BLOCK_LATIN_EXTENDED_ADDITIONAL 70
#define UCDN_BLOCK_GREEK_EXTENDED 71
#define UCDN_BLOCK_GENERAL_PUNCTUATION 72
#define UCDN_BLOCK_SUPERSCRIPTS_AND_SUBSCRIPTS 73
#define UCDN_BLOCK_CURRENCY_SYMBOLS 74
#define UCDN_BLOCK_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS 75
#define UCDN_BLOCK_LETTERLIKE_SYMBOLS 76
#define UCDN_BLOCK_NUMBER_FORMS 77
#define UCDN_BLOCK_ARROWS 78
#define UCDN_BLOCK_MATHEMATICAL_OPERATORS 79
#define UCDN_BLOCK_MISCELLANEOUS_TECHNICAL 80
#define UCDN_BLOCK_CONTROL_PICTURES 81
#define UCDN_BLOCK_OPTICAL_CHARACTER_RECOGNITION 82
#define UCDN_BLOCK_ENCLOSED_ALPHANUMERICS 83
#define UCDN_BLOCK_BOX_DRAWING 84
#define UCDN_BLOCK_BLOCK_ELEMENTS 85
#define UCDN_BLOCK_GEOMETRIC_SHAPES 86
#define UCDN_BLOCK_MISCELLANEOUS_SYMBOLS 87
#define UCDN_BLOCK_DINGBATS 88
#define UCDN_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A 89
#define UCDN_BLOCK_SUPPLEMENTAL_ARROWS_A 90
#define UCDN_BLOCK_BRAILLE_PATTERNS 91
#define UCDN_BLOCK_SUPPLEMENTAL_ARROWS_B 92
#define UCDN_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B 93
#define UCDN_BLOCK_SUPPLEMENTAL_MATHEMATICAL_OPERATORS 94
#define UCDN_BLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS 95
#define UCDN_BLOCK_GLAGOLITIC 96
#define UCDN_BLOCK_LATIN_EXTENDED_C 97
#define UCDN_BLOCK_COPTIC 98
#define UCDN_BLOCK_GEORGIAN_SUPPLEMENT 99
#define UCDN_BLOCK_TIFINAGH 100
#define UCDN_BLOCK_ETHIOPIC_EXTENDED 101
#define UCDN_BLOCK_CYRILLIC_EXTENDED_A 102
#define UCDN_BLOCK_SUPPLEMENTAL_PUNCTUATION 103
#define UCDN_BLOCK_CJK_RADICALS_SUPPLEMENT 104
#define UCDN_BLOCK_KANGXI_RADICALS 105
#define UCDN_BLOCK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS 106
#define UCDN_BLOCK_CJK_SYMBOLS_AND_PUNCTUATION 107
#define UCDN_BLOCK_HIRAGANA 108
#define UCDN_BLOCK_KATAKANA 109
#define UCDN_BLOCK_BOPOMOFO 110
#define UCDN_BLOCK_HANGUL_COMPATIBILITY_JAMO 111
#define UCDN_BLOCK_KANBUN 112
#define UCDN_BLOCK_BOPOMOFO_EXTENDED 113
#define UCDN_BLOCK_CJK_STROKES 114
#define UCDN_BLOCK_KATAKANA_PHONETIC_EXTENSIONS 115
#define UCDN_BLOCK_ENCLOSED_CJK_LETTERS_AND_MONTHS 116
#define UCDN_BLOCK_CJK_COMPATIBILITY 117
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A 118
#define UCDN_BLOCK_YIJING_HEXAGRAM_SYMBOLS 119
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS 120
#define UCDN_BLOCK_YI_SYLLABLES 121
#define UCDN_BLOCK_YI_RADICALS 122
#define UCDN_BLOCK_LISU 123
#define UCDN_BLOCK_VAI 124
#define UCDN_BLOCK_CYRILLIC_EXTENDED_B 125
#define UCDN_BLOCK_BAMUM 126
#define UCDN_BLOCK_MODIFIER_TONE_LETTERS 127
#define UCDN_BLOCK_LATIN_EXTENDED_D 128
#define UCDN_BLOCK_SYLOTI_NAGRI 129
#define UCDN_BLOCK_COMMON_INDIC_NUMBER_FORMS 130
#define UCDN_BLOCK_PHAGS_PA 131
#define UCDN_BLOCK_SAURASHTRA 132
#define UCDN_BLOCK_DEVANAGARI_EXTENDED 133
#define UCDN_BLOCK_KAYAH_LI 134
#define UCDN_BLOCK_REJANG 135
#define UCDN_BLOCK_HANGUL_JAMO_EXTENDED_A 136
#define UCDN_BLOCK_JAVANESE 137
#define UCDN_BLOCK_MYANMAR_EXTENDED_B 138
#define UCDN_BLOCK_CHAM 139
#define UCDN_BLOCK_MYANMAR_EXTENDED_A 140
#define UCDN_BLOCK_TAI_VIET 141
#define UCDN_BLOCK_MEETEI_MAYEK_EXTENSIONS 142
#define UCDN_BLOCK_ETHIOPIC_EXTENDED_A 143
#define UCDN_BLOCK_LATIN_EXTENDED_E 144
#define UCDN_BLOCK_CHEROKEE_SUPPLEMENT 145
#define UCDN_BLOCK_MEETEI_MAYEK 146
#define UCDN_BLOCK_HANGUL_SYLLABLES 147
#define UCDN_BLOCK_HANGUL_JAMO_EXTENDED_B 148
#define UCDN_BLOCK_HIGH_SURROGATES 149
#define UCDN_BLOCK_HIGH_PRIVATE_USE_SURROGATES 150
#define UCDN_BLOCK_LOW_SURROGATES 151
#define UCDN_BLOCK_PRIVATE_USE_AREA 152
#define UCDN_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS 153
#define UCDN_BLOCK_ALPHABETIC_PRESENTATION_FORMS 154
#define UCDN_BLOCK_ARABIC_PRESENTATION_FORMS_A 155
#define UCDN_BLOCK_VARIATION_SELECTORS 156
#define UCDN_BLOCK_VERTICAL_FORMS 157
#define UCDN_BLOCK_COMBINING_HALF_MARKS 158
#define UCDN_BLOCK_CJK_COMPATIBILITY_FORMS 159
#define UCDN_BLOCK_SMALL_FORM_VARIANTS 160
#define UCDN_BLOCK_ARABIC_PRESENTATION_FORMS_B 161
#define UCDN_BLOCK_HALFWIDTH_AND_FULLWIDTH_FORMS 162
#define UCDN_BLOCK_SPECIALS 163
#define UCDN_BLOCK_LINEAR_B_SYLLABARY 164
#define UCDN_BLOCK_LINEAR_B_IDEOGRAMS 165
#define UCDN_BLOCK_AEGEAN_NUMBERS 166
#define UCDN_BLOCK_ANCIENT_GREEK_NUMBERS 167
#define UCDN_BLOCK_ANCIENT_SYMBOLS 168
#define UCDN_BLOCK_PHAISTOS_DISC 169
#define UCDN_BLOCK_LYCIAN 170
#define UCDN_BLOCK_CARIAN 171
#define UCDN_BLOCK_COPTIC_EPACT_NUMBERS 172
#define UCDN_BLOCK_OLD_ITALIC 173
#define UCDN_BLOCK_GOTHIC 174
#define UCDN_BLOCK_OLD_PERMIC 175
#define UCDN_BLOCK_UGARITIC 176
#define UCDN_BLOCK_OLD_PERSIAN 177
#define UCDN_BLOCK_DESERET 178
#define UCDN_BLOCK_SHAVIAN 179
#define UCDN_BLOCK_OSMANYA 180
#define UCDN_BLOCK_OSAGE 181
#define UCDN_BLOCK_ELBASAN 182
#define UCDN_BLOCK_CAUCASIAN_ALBANIAN 183
#define UCDN_BLOCK_LINEAR_A 184
#define UCDN_BLOCK_CYPRIOT_SYLLABARY 185
#define UCDN_BLOCK_IMPERIAL_ARAMAIC 186
#define UCDN_BLOCK_PALMYRENE 187
#define UCDN_BLOCK_NABATAEAN 188
#define UCDN_BLOCK_HATRAN 189
#define UCDN_BLOCK_PHOENICIAN 190
#define UCDN_BLOCK_LYDIAN 191
#define UCDN_BLOCK_MEROITIC_HIEROGLYPHS 192
#define UCDN_BLOCK_MEROITIC_CURSIVE 193
#define UCDN_BLOCK_KHAROSHTHI 194
#define UCDN_BLOCK_OLD_SOUTH_ARABIAN 195
#define UCDN_BLOCK_OLD_NORTH_ARABIAN 196
#define UCDN_BLOCK_MANICHAEAN 197
#define UCDN_BLOCK_AVESTAN 198
#define UCDN_BLOCK_INSCRIPTIONAL_PARTHIAN 199
#define UCDN_BLOCK_INSCRIPTIONAL_PAHLAVI 200
#define UCDN_BLOCK_PSALTER_PAHLAVI 201
#define UCDN_BLOCK_OLD_TURKIC 202
#define UCDN_BLOCK_OLD_HUNGARIAN 203
#define UCDN_BLOCK_HANIFI_ROHINGYA 204
#define UCDN_BLOCK_RUMI_NUMERAL_SYMBOLS 205
#define UCDN_BLOCK_OLD_SOGDIAN 206
#define UCDN_BLOCK_SOGDIAN 207
#define UCDN_BLOCK_ELYMAIC 208
#define UCDN_BLOCK_BRAHMI 209
#define UCDN_BLOCK_KAITHI 210
#define UCDN_BLOCK_SORA_SOMPENG 211
#define UCDN_BLOCK_CHAKMA 212
#define UCDN_BLOCK_MAHAJANI 213
#define UCDN_BLOCK_SHARADA 214
#define UCDN_BLOCK_SINHALA_ARCHAIC_NUMBERS 215
#define UCDN_BLOCK_KHOJKI 216
#define UCDN_BLOCK_MULTANI 217
#define UCDN_BLOCK_KHUDAWADI 218
#define UCDN_BLOCK_GRANTHA 219
#define UCDN_BLOCK_NEWA 220
#define UCDN_BLOCK_TIRHUTA 221
#define UCDN_BLOCK_SIDDHAM 222
#define UCDN_BLOCK_MODI 223
#define UCDN_BLOCK_MONGOLIAN_SUPPLEMENT 224
#define UCDN_BLOCK_TAKRI 225
#define UCDN_BLOCK_AHOM 226
#define UCDN_BLOCK_DOGRA 227
#define UCDN_BLOCK_WARANG_CITI 228
#define UCDN_BLOCK_NANDINAGARI 229
#define UCDN_BLOCK_ZANABAZAR_SQUARE 230
#define UCDN_BLOCK_SOYOMBO 231
#define UCDN_BLOCK_PAU_CIN_HAU 232
#define UCDN_BLOCK_BHAIKSUKI 233
#define UCDN_BLOCK_MARCHEN 234
#define UCDN_BLOCK_MASARAM_GONDI 235
#define UCDN_BLOCK_GUNJALA_GONDI 236
#define UCDN_BLOCK_MAKASAR 237
#define UCDN_BLOCK_TAMIL_SUPPLEMENT 238
#define UCDN_BLOCK_CUNEIFORM 239
#define UCDN_BLOCK_CUNEIFORM_NUMBERS_AND_PUNCTUATION 240
#define UCDN_BLOCK_EARLY_DYNASTIC_CUNEIFORM 241
#define UCDN_BLOCK_EGYPTIAN_HIEROGLYPHS 242
#define UCDN_BLOCK_EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS 243
#define UCDN_BLOCK_ANATOLIAN_HIEROGLYPHS 244
#define UCDN_BLOCK_BAMUM_SUPPLEMENT 245
#define UCDN_BLOCK_MRO 246
#define UCDN_BLOCK_BASSA_VAH 247
#define UCDN_BLOCK_PAHAWH_HMONG 248
#define UCDN_BLOCK_MEDEFAIDRIN 249
#define UCDN_BLOCK_MIAO 250
#define UCDN_BLOCK_IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION 251
#define UCDN_BLOCK_TANGUT 252
#define UCDN_BLOCK_TANGUT_COMPONENTS 253
#define UCDN_BLOCK_KANA_SUPPLEMENT 254
#define UCDN_BLOCK_KANA_EXTENDED_A 255
#define UCDN_BLOCK_SMALL_KANA_EXTENSION 256
#define UCDN_BLOCK_NUSHU 257
#define UCDN_BLOCK_DUPLOYAN 258
#define UCDN_BLOCK_SHORTHAND_FORMAT_CONTROLS 259
#define UCDN_BLOCK_BYZANTINE_MUSICAL_SYMBOLS 260
#define UCDN_BLOCK_MUSICAL_SYMBOLS 261
#define UCDN_BLOCK_ANCIENT_GREEK_MUSICAL_NOTATION 262
#define UCDN_BLOCK_MAYAN_NUMERALS 263
#define UCDN_BLOCK_TAI_XUAN_JING_SYMBOLS 264
#define UCDN_BLOCK_COUNTING_ROD_NUMERALS 265
#define UCDN_BLOCK_MATHEMATICAL_ALPHANUMERIC_SYMBOLS 266
#define UCDN_BLOCK_SUTTON_SIGNWRITING 267
#define UCDN_BLOCK_GLAGOLITIC_SUPPLEMENT 268
#define UCDN_BLOCK_NYIAKENG_PUACHUE_HMONG 269
#define UCDN_BLOCK_WANCHO 270
#define UCDN_BLOCK_MENDE_KIKAKUI 271
#define UCDN_BLOCK_ADLAM 272
#define UCDN_BLOCK_INDIC_SIYAQ_NUMBERS 273
#define UCDN_BLOCK_OTTOMAN_SIYAQ_NUMBERS 274
#define UCDN_BLOCK_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS 275
#define UCDN_BLOCK_MAHJONG_TILES 276
#define UCDN_BLOCK_DOMINO_TILES 277
#define UCDN_BLOCK_PLAYING_CARDS 278
#define UCDN_BLOCK_ENCLOSED_ALPHANUMERIC_SUPPLEMENT 279
#define UCDN_BLOCK_ENCLOSED_IDEOGRAPHIC_SUPPLEMENT 280
#define UCDN_BLOCK_MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS 281
#define UCDN_BLOCK_EMOTICONS 282
#define UCDN_BLOCK_ORNAMENTAL_DINGBATS 283
#define UCDN_BLOCK_TRANSPORT_AND_MAP_SYMBOLS 284
#define UCDN_BLOCK_ALCHEMICAL_SYMBOLS 285
#define UCDN_BLOCK_GEOMETRIC_SHAPES_EXTENDED 286
#define UCDN_BLOCK_SUPPLEMENTAL_ARROWS_C 287
#define UCDN_BLOCK_SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS 288
#define UCDN_BLOCK_CHESS_SYMBOLS 289
#define UCDN_BLOCK_SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A 290
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B 291
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C 292
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D 293
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E 294
#define UCDN_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F 295
#define UCDN_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT 296
#define UCDN_BLOCK_TAGS 297
#define UCDN_BLOCK_VARIATION_SELECTORS_SUPPLEMENT 298
#define UCDN_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_A 299
#define UCDN_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_B 300

#define UCDN_LINEBREAK_CLASS_OP 0
#define UCDN_LINEBREAK_CLASS_CL 1
#define UCDN_LINEBREAK_CLASS_CP 2
#define UCDN_LINEBREAK_CLASS_QU 3
#define UCDN_LINEBREAK_CLASS_GL 4
#define UCDN_LINEBREAK_CLASS_NS 5
#define UCDN_LINEBREAK_CLASS_EX 6
#define UCDN_LINEBREAK_CLASS_SY 7
#define UCDN_LINEBREAK_CLASS_IS 8
#define UCDN_LINEBREAK_CLASS_PR 9
#define UCDN_LINEBREAK_CLASS_PO 10
#define UCDN_LINEBREAK_CLASS_NU 11
#define UCDN_LINEBREAK_CLASS_AL 12
#define UCDN_LINEBREAK_CLASS_HL 13
#define UCDN_LINEBREAK_CLASS_ID 14
#define UCDN_LINEBREAK_CLASS_IN 15
#define UCDN_LINEBREAK_CLASS_HY 16
#define UCDN_LINEBREAK_CLASS_BA 17
#define UCDN_LINEBREAK_CLASS_BB 18
#define UCDN_LINEBREAK_CLASS_B2 19
#define UCDN_LINEBREAK_CLASS_ZW 20
#define UCDN_LINEBREAK_CLASS_CM 21
#define UCDN_LINEBREAK_CLASS_WJ 22
#define UCDN_LINEBREAK_CLASS_H2 23
#define UCDN_LINEBREAK_CLASS_H3 24
#define UCDN_LINEBREAK_CLASS_JL 25
#define UCDN_LINEBREAK_CLASS_JV 26
#define UCDN_LINEBREAK_CLASS_JT 27
#define UCDN_LINEBREAK_CLASS_RI 28
#define UCDN_LINEBREAK_CLASS_AI 29
#define UCDN_LINEBREAK_CLASS_BK 30
#define UCDN_LINEBREAK_CLASS_CB 31
#define UCDN_LINEBREAK_CLASS_CJ 32
#define UCDN_LINEBREAK_CLASS_CR 33
#define UCDN_LINEBREAK_CLASS_LF 34
#define UCDN_LINEBREAK_CLASS_NL 35
#define UCDN_LINEBREAK_CLASS_SA 36
#define UCDN_LINEBREAK_CLASS_SG 37
#define UCDN_LINEBREAK_CLASS_SP 38
#define UCDN_LINEBREAK_CLASS_XX 39
#define UCDN_LINEBREAK_CLASS_ZWJ 40
#define UCDN_LINEBREAK_CLASS_EB 41
#define UCDN_LINEBREAK_CLASS_EM 42

#define UCDN_GENERAL_CATEGORY_CC 0
#define UCDN_GENERAL_CATEGORY_CF 1
#define UCDN_GENERAL_CATEGORY_CN 2
#define UCDN_GENERAL_CATEGORY_CO 3
#define UCDN_GENERAL_CATEGORY_CS 4
#define UCDN_GENERAL_CATEGORY_LL 5
#define UCDN_GENERAL_CATEGORY_LM 6
#define UCDN_GENERAL_CATEGORY_LO 7
#define UCDN_GENERAL_CATEGORY_LT 8
#define UCDN_GENERAL_CATEGORY_LU 9
#define UCDN_GENERAL_CATEGORY_MC 10
#define UCDN_GENERAL_CATEGORY_ME 11
#define UCDN_GENERAL_CATEGORY_MN 12
#define UCDN_GENERAL_CATEGORY_ND 13
#define UCDN_GENERAL_CATEGORY_NL 14
#define UCDN_GENERAL_CATEGORY_NO 15
#define UCDN_GENERAL_CATEGORY_PC 16
#define UCDN_GENERAL_CATEGORY_PD 17
#define UCDN_GENERAL_CATEGORY_PE 18
#define UCDN_GENERAL_CATEGORY_PF 19
#define UCDN_GENERAL_CATEGORY_PI 20
#define UCDN_GENERAL_CATEGORY_PO 21
#define UCDN_GENERAL_CATEGORY_PS 22
#define UCDN_GENERAL_CATEGORY_SC 23
#define UCDN_GENERAL_CATEGORY_SK 24
#define UCDN_GENERAL_CATEGORY_SM 25
#define UCDN_GENERAL_CATEGORY_SO 26
#define UCDN_GENERAL_CATEGORY_ZL 27
#define UCDN_GENERAL_CATEGORY_ZP 28
#define UCDN_GENERAL_CATEGORY_ZS 29

#define UCDN_BIDI_CLASS_L 0
#define UCDN_BIDI_CLASS_LRE 1
#define UCDN_BIDI_CLASS_LRO 2
#define UCDN_BIDI_CLASS_R 3
#define UCDN_BIDI_CLASS_AL 4
#define UCDN_BIDI_CLASS_RLE 5
#define UCDN_BIDI_CLASS_RLO 6
#define UCDN_BIDI_CLASS_PDF 7
#define UCDN_BIDI_CLASS_EN 8
#define UCDN_BIDI_CLASS_ES 9
#define UCDN_BIDI_CLASS_ET 10
#define UCDN_BIDI_CLASS_AN 11
#define UCDN_BIDI_CLASS_CS 12
#define UCDN_BIDI_CLASS_NSM 13
#define UCDN_BIDI_CLASS_BN 14
#define UCDN_BIDI_CLASS_B 15
#define UCDN_BIDI_CLASS_S 16
#define UCDN_BIDI_CLASS_WS 17
#define UCDN_BIDI_CLASS_ON 18
#define UCDN_BIDI_CLASS_LRI 19
#define UCDN_BIDI_CLASS_RLI 20
#define UCDN_BIDI_CLASS_FSI 21
#define UCDN_BIDI_CLASS_PDI 22

#define UCDN_BIDI_PAIRED_BRACKET_TYPE_OPEN 0
#define UCDN_BIDI_PAIRED_BRACKET_TYPE_CLOSE 1
#define UCDN_BIDI_PAIRED_BRACKET_TYPE_NONE 2

/**
 * Return version of the Unicode database.
 *
 * @return Unicode database version
 */
const char *ucdn_get_unicode_version(void);

/**
 * Get combining class of a codepoint.
 *
 * @param code Unicode codepoint
 * @return combining class value, as defined in UAX#44
 */
int ucdn_get_combining_class(uint32_t code);

/**
 * Get east-asian width of a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_EAST_ASIAN_* and as defined in UAX#11.
 */
int ucdn_get_east_asian_width(uint32_t code);

/**
 * Get general category of a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_GENERAL_CATEGORY_* and as defined in
 * UAX#44.
 */
int ucdn_get_general_category(uint32_t code);

/**
 * Get bidirectional class of a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_BIDI_CLASS_* and as defined in UAX#44.
 */
int ucdn_get_bidi_class(uint32_t code);

/**
 * Get script of a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_SCRIPT_* and as defined in UAX#24.
 */
int ucdn_get_script(uint32_t code);

/**
 * Get block of a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_BLOCK_* and as defined in UAX#44.
 */
int ucdn_get_block(uint32_t code);

/**
 * Get unresolved linebreak class of a codepoint. This does not take
 * rule LB1 of UAX#14 into account. See ucdn_get_resolved_linebreak_class()
 * for resolved linebreak classes.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_LINEBREAK_* and as defined in UAX#14.
 */
int ucdn_get_linebreak_class(uint32_t code);

/**
 * Get resolved linebreak class of a codepoint. This resolves characters
 * in the AI, SG, XX, SA and CJ classes according to rule LB1 of UAX#14.
 * In addition the CB class is resolved as the equivalent B2 class and
 * the NL class is resolved as the equivalent BK class.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_LINEBREAK_* and as defined in UAX#14.
 */
int ucdn_get_resolved_linebreak_class(uint32_t code);

/**
 * Check if codepoint can be mirrored.
 *
 * @param code Unicode codepoint
 * @return 1 if mirrored character exists, otherwise 0
 */
int ucdn_get_mirrored(uint32_t code);

/**
 * Mirror a codepoint.
 *
 * @param code Unicode codepoint
 * @return mirrored codepoint or the original codepoint if no
 * mirrored character exists
 */
uint32_t ucdn_mirror(uint32_t code);

/**
 * Get paired bracket for a codepoint.
 *
 * @param code Unicode codepoint
 * @return paired bracket codepoint or the original codepoint if no
 * paired bracket character exists
 */
uint32_t ucdn_paired_bracket(uint32_t code);

/**
 * Get paired bracket type for a codepoint.
 *
 * @param code Unicode codepoint
 * @return value according to UCDN_BIDI_PAIRED_BRACKET_TYPE_* and as defined
 * in UAX#9.
 *
 */
int ucdn_paired_bracket_type(uint32_t code);

/**
 * Pairwise canonical decomposition of a codepoint. This includes
 * Hangul Jamo decomposition (see chapter 3.12 of the Unicode core
 * specification).
 *
 * Hangul is decomposed into L and V jamos for LV forms, and an
 * LV precomposed syllable and a T jamo for LVT forms.
 *
 * @param code Unicode codepoint
 * @param a filled with first codepoint of decomposition
 * @param b filled with second codepoint of decomposition, or 0
 * @return success
 */
int ucdn_decompose(uint32_t code, uint32_t *a, uint32_t *b);

/**
 * Compatibility decomposition of a codepoint.
 *
 * @param code Unicode codepoint
 * @param decomposed filled with decomposition, must be able to hold 18
 * characters
 * @return length of decomposition or 0 in case none exists
 */
int ucdn_compat_decompose(uint32_t code, uint32_t *decomposed);

/**
 * Pairwise canonical composition of two codepoints. This includes
 * Hangul Jamo composition (see chapter 3.12 of the Unicode core
 * specification).
 *
 * Hangul composition expects either L and V jamos, or an LV
 * precomposed syllable and a T jamo. This is exactly the inverse
 * of pairwise Hangul decomposition.
 *
 * @param code filled with composition
 * @param a first codepoint
 * @param b second codepoint
 * @return success
 */
int ucdn_compose(uint32_t *code, uint32_t a, uint32_t b);

#ifdef __cplusplus
}
#endif

#endif
